### ISSUE TITLE
undefined method `order_subtotal'

### ISSUE THREAD

**Issue by drc37** [spree-contrib/spree_rdr_theme#17]
Found another little issue in file: 
app / overrides / spree / orders / replace_cart_detail.rb

```
Deface: 'replace_cart_detail' matched 1 times with '#cart-detail[data-hook]'
Deface: [WARNING] No :original defined for 'replace_cart_detail', you should change its definition to include:
 :original => '58b3ef8e96357ea004ae8e6088f296bfb51c7171' 
  Rendered /usr/local/rvm/gems/ruby-1.9.3-p194/gems/spree_core-1.3.2/app/views/spree/orders/_form.html.erb (163.3ms)
  Rendered /usr/local/rvm/gems/ruby-1.9.3-p194/gems/spree_core-1.3.2/app/views/spree/orders/edit.html.erb within spree/layouts/spree_application (176.8ms)
Completed 500 Internal Server Error in 321ms

ActionView::Template::Error (undefined method `order_subtotal' for #<#<Class:0x007fba16922980>:0x007fba141d17a0>):
    23: <tr class="totals">
    24: <td colspan="6"> </td>
    25:       <td colspan="2" class="totals">
    26:         <%= t(:subtotal) %>: <span class="order-total"><%= order_subtotal(@order) %></span>
    27:       </td>
    28:     </tr>
    29: </tbody>
  spree_core (1.3.2) app/helpers/spree/base_helper.rb:162:in `method_missing'
  spree_core (1.3.2) app/views/spree/orders/_form.html.erb:26:in `_3ca59c3929d4edb59c8b96c6f787b38b'
  actionpack (3.2.13) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.13) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.13) lib/action_view/template.rb:143:in `render'

```

**Comment by radar** [comment]
@drc37 I think I've fixed this issue now. Could you please try the 1-3-stable branch and let me know if that works?

```
gem 'spree_rdr_theme', :github => "spree/spree_rdr_theme", :branch => "1-3-stable"
```
