### ISSUE TITLE
undefined method `all'

### ISSUE THREAD

**Issue by galievruslan** [spree-contrib/spree_rdr_theme#19]
hello
I'm using Ruby 2.2.1, Rails 4.2.0, Spree 3.1.0beta, spree_rdr_theme 1.0
When you try to install the theme:

```
rails g spree_rdr_theme: install
```

error:

```
root@ruby:/team/store# /usr/local/rvm/gems/ruby-2.2.1/bundler/gems/spree_rdr_theme-b5d6a80caa6b/app/overrides/spree/products/add_related_products_to_cart_form.rb:1:in `<top (required)>': undefined method `all' for #<Rails::Engine::Railties:0xb4405d8> (NoMethodError)
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:99:in `block (2 levels) in enumerate_and_load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:98:in `glob'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:98:in `block in enumerate_and_load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:91:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:91:in `enumerate_and_load'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:85:in `load_overrides'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:68:in `block in load_all'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:66:in `each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/environment.rb:66:in `load_all'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/deface-1.0.1/lib/deface/railtie.rb:12:in `activate'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `block in simple'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_prepare_callbacks'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `call'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
        from /team/store/config/environment.rb:5:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/spring-1.3.3/lib/spring/application.rb:92:in `preload'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/spring-1.3.3/lib/spring/application.rb:143:in `serve'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/spring-1.3.3/lib/spring/application.rb:131:in `block in run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/spring-1.3.3/lib/spring/application.rb:125:in `loop'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/spring-1.3.3/lib/spring/application.rb:125:in `run'
        from /usr/local/rvm/gems/ruby-2.2.1/gems/spring-1.3.3/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
```

What am I doing wrong?

**Comment by JDutil** [comment]
This theme is no longer maintained, and is not compatible with Spree 2+ or so.

**Comment by palpandiR** [comment]
I am also got the same issue .
